name: Discord Webhook Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          BRANCH_NAME=${GITHUB_REF##*/}
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"🚀 Nouveau commit sur \`${BRANCH_NAME}\` par \`${GITHUB_ACTOR}\`:\n👉 [${COMMIT_MESSAGE}](${COMMIT_URL})\"}" \
               $DISCORD_WEBHOOK
